import manifest from '../../data/skillExamProfiles.json'

// ─────────────────────────────────────────────────────────────────────────────
// Read side of the tier 3 exam profile. The data is generated by
// scripts/build-skill-exam-profiles.ts from data/exam-audit — never authored.
//
// A profile is always scoped to a BOARD and a TIER, because those are the two
// things a student actually sits. Never show a Foundation candidate a claim
// derived from Higher papers.
// ─────────────────────────────────────────────────────────────────────────────

export type BareBand = 'never' | 'rarely' | 'sometimes' | 'usually' | 'almost always'

export type SkillExamProfile = {
  skillId: string
  board: string
  tier: string
  parts: number
  marks: number
  papersSeen: number
  papersTotal: number
  markRange: [number, number]
  framing: Record<string, number>
  barePct: number
  bareBand: BareBand
  calc: Record<string, number>
  markSplits: string[]
  chainedPct: number
  traps: string[]
  sufficient: boolean
}

type Manifest = {
  generatedAt: string
  minParts: number
  slices: { board: string; tier: string; papers: string[]; series: string[]; skillsPresent: number; skillsSufficient: number }[]
  profiles: Record<string, SkillExamProfile>
}

const data = manifest as unknown as Manifest

export type Tier = 'foundation' | 'higher'

/** The audit codes tiers with a capital; the app uses lowercase throughout. */
const auditTier = (tier: Tier) => (tier === 'higher' ? 'Higher' : 'Foundation')

/** Exam boards we hold coded papers for, in display order. */
export const codedBoards = (): string[] =>
  [...new Set(data.slices.map(s => s.board))].sort()

export const generatedAt = () => data.generatedAt
export const minParts = () => data.minParts

/**
 * The profile for one skill on one board and tier, or null when we have no
 * coded evidence. Callers must also check `.sufficient` before rendering any
 * claim — a profile below the evidence bar is real data but too thin to say
 * anything true with.
 */
export function getExamProfile(skillId: string, board: string, tier: Tier): SkillExamProfile | null {
  return data.profiles[`${board}|${auditTier(tier)}|${skillId}`] ?? null
}

/** True when there is enough coded evidence to render the panel at all. */
export function hasUsableProfile(skillId: string, board: string, tier: Tier): boolean {
  return getExamProfile(skillId, board, tier)?.sufficient ?? false
}

/** Which papers a slice was built from — shown as provenance under the panel. */
export function sliceProvenance(board: string, tier: Tier) {
  return data.slices.find(s => s.board === board && s.tier === auditTier(tier)) ?? null
}

// ── Phrasing ─────────────────────────────────────────────────────────────────

/**
 * The framing labels as a student would read them. Keys match the `framing`
 * vocabulary in the coded papers.
 */
export const FRAMING_LABELS: Record<string, string> = {
  bare:             'Asked plainly',
  real_world:       'Wrapped in a context',
  multi_route:      'More than one valid route',
  decision_justify: 'Decide and justify',
  consequence:      'What happens if something changes',
  given_formula:    'Formula given, inputs to choose',
  inverse_operand:  'Given the answer, find the input',
}

/**
 * The headline sentence about how often the skill is asked plainly. Derived
 * from the band, so a newly coded series rewrites it without anyone editing
 * copy. Deliberately not authored per skill.
 */
export function bareClaim(p: SkillExamProfile, skillName: string): string {
  const lower = skillName.toLowerCase()
  switch (p.bareBand) {
    case 'never':
      return `You're rarely directly told that a question is about ${lower}. It will usually be written as a real-world problem.`
    case 'rarely':
      return `You are rarely told it is a ${lower} question — it is nearly always dressed as something else.`
    case 'sometimes':
      return `Sometimes you are asked outright, but most of the time ${lower} is dressed as something else.`
    case 'usually':
      return `Usually you are asked outright, though it is sometimes wrapped in a context.`
    case 'almost always':
      return `You are almost always asked outright — recognising it is not the hard part here.`
  }
}

/** Whether the mark scheme typically chains, phrased for a student. */
export function chainClaim(p: SkillExamProfile): string | null {
  if (p.chainedPct < 25) return null
  const how = p.chainedPct >= 60 ? 'usually' : 'often'
  return `The marks ${how} chain, so a wrong first step can block credit on everything after it.`
}

/** Calculator split, phrased. Null when there is no clear lean. */
export function calcClaim(p: SkillExamProfile): string | null {
  const calc = p.calc.calc ?? 0
  const non = p.calc.non_calc ?? 0
  const total = calc + non
  if (total < 3) return null
  if (calc / total >= 0.75) return 'Nearly always on a calculator paper.'
  if (non / total >= 0.75) return 'Nearly always on a non-calculator paper.'
  return 'Appears on both calculator and non-calculator papers.'
}

/** Framing counts as sorted display rows, excluding `bare`. */
export function dressedFramings(p: SkillExamProfile): { key: string; label: string; count: number }[] {
  return Object.entries(p.framing)
    .filter(([k]) => k !== 'bare')
    .sort((a, b) => b[1] - a[1])
    .map(([key, count]) => ({ key, label: FRAMING_LABELS[key] ?? key, count }))
}
