import manifest from '../../data/skillExamProfiles.json'

// ─────────────────────────────────────────────────────────────────────────────
// Read side of the tier 3 exam profile. The data is generated by
// scripts/build-skill-exam-profiles.ts from data/exam-audit — never authored.
//
// A profile is always scoped to a BOARD and a TIER, because those are the two
// things a student actually sits. Never show a Foundation candidate a claim
// derived from Higher papers.
// ─────────────────────────────────────────────────────────────────────────────

export type BareBand = 'never' | 'rarely' | 'sometimes' | 'usually' | 'almost always'

export type SkillExamProfile = {
  skillId: string
  board: string
  tier: string
  parts: number
  marks: number
  papersSeen: number
  papersTotal: number
  markRange: [number, number]
  framing: Record<string, number>
  barePct: number
  bareBand: BareBand
  calc: Record<string, number>
  markSplits: string[]
  chainedPct: number
  traps: string[]
  sufficient: boolean
}

type Manifest = {
  generatedAt: string
  minParts: number
  slices: { board: string; tier: string; papers: string[]; series: string[]; skillsPresent: number; skillsSufficient: number }[]
  profiles: Record<string, SkillExamProfile>
}

const data = manifest as unknown as Manifest

export type Tier = 'foundation' | 'higher'

/** The audit codes tiers with a capital; the app uses lowercase throughout. */
const auditTier = (tier: Tier) => (tier === 'higher' ? 'Higher' : 'Foundation')

/** Exam boards we hold coded papers for, in display order. */
export const codedBoards = (): string[] =>
  [...new Set(data.slices.map(s => s.board))].sort()

export const generatedAt = () => data.generatedAt
export const minParts = () => data.minParts

/**
 * The profile for one skill on one board and tier, or null when we have no
 * coded evidence. Callers must also check `.sufficient` before rendering any
 * claim — a profile below the evidence bar is real data but too thin to say
 * anything true with.
 */
export function getExamProfile(skillId: string, board: string, tier: Tier): SkillExamProfile | null {
  return data.profiles[`${board}|${auditTier(tier)}|${skillId}`] ?? null
}

/** True when there is enough coded evidence to render the panel at all. */
export function hasUsableProfile(skillId: string, board: string, tier: Tier): boolean {
  return getExamProfile(skillId, board, tier)?.sufficient ?? false
}

/** Which papers a slice was built from — shown as provenance under the panel. */
export function sliceProvenance(board: string, tier: Tier) {
  return data.slices.find(s => s.board === board && s.tier === auditTier(tier)) ?? null
}

// ── Phrasing ─────────────────────────────────────────────────────────────────

/**
 * The framing labels as a student would read them. Keys match the `framing`
 * vocabulary in the coded papers.
 */
export const FRAMING_LABELS: Record<string, string> = {
  bare:             'Asked plainly',
  real_world:       'Wrapped in a context',
  multi_route:      'More than one valid route',
  decision_justify: 'Decide and justify',
  consequence:      'What happens if something changes',
  given_formula:    'Formula given, inputs to choose',
  inverse_operand:  'Given the answer, find the input',
}

/**
 * How the skill is dressed when it is NOT asked outright, phrased as the tail
 * of a sentence ("It will usually be …").
 *
 * Derived from whichever framing dominates rather than assumed. The claim used
 * to hardcode "written as a real-world problem", which is true for proportion
 * but would be a plain falsehood for a skill dominated by multi_route or
 * decision_justify. Returns null when there is nothing but bare framing, so
 * callers can drop the clause instead of inventing one.
 */
function dominantDressing(p: SkillExamProfile): string | null {
  // Every phrase must read correctly after "be", because it is dropped into
  // three different frames: "It will usually be ___", "more often it will be
  // ___", and "though it is sometimes ___". Keep them short participle phrases
  // with no trailing clause — a "…, so …" tail parses in the first frame and
  // falls apart in the third.
  const PHRASES: Record<string, string> = {
    real_world:       'written as a real-world problem',
    multi_route:      'solvable more than one way',
    decision_justify: 'asked as a decision you have to justify',
    consequence:      'framed as what happens when something else changes',
    given_formula:    'given with the formula supplied, leaving you to choose the inputs',
    inverse_operand:  'run backwards, giving you the answer and asking for the input',
  }

  const top = Object.entries(p.framing)
    .filter(([k]) => k !== 'bare')
    .sort((a, b) => b[1] - a[1])[0]

  return top ? (PHRASES[top[0]] ?? null) : null
}

/**
 * The headline sentence about how often the skill is asked plainly.
 *
 * Both halves are derived — the band from the bare percentage, the dressing
 * from the dominant framing — so a newly coded series rewrites this without
 * anyone editing copy. That is the whole point: when the 2025 papers added
 * three bare proportion questions, this moved from "never" to "rarely" on its
 * own. Deliberately not authored per skill.
 */
export function bareClaim(p: SkillExamProfile, skillName: string): string {
  const lower = skillName.toLowerCase()
  const dressing = dominantDressing(p)
  const told = `directly told that a question is about ${lower}`

  switch (p.bareBand) {
    case 'never':
      return dressing
        ? `You're never directly told that a question is about ${lower}. It will always be ${dressing}.`
        : `You're never ${told}.`
    case 'rarely':
      return dressing
        ? `You're rarely ${told}. It will usually be ${dressing}.`
        : `You're rarely ${told}.`
    case 'sometimes':
      return dressing
        ? `You're sometimes ${told}, but more often it will be ${dressing}.`
        : `You're sometimes ${told}.`
    case 'usually':
      return dressing
        ? `You're usually ${told}, though it is sometimes ${dressing}.`
        : `You're usually ${told}.`
    case 'almost always':
      return `You're almost always ${told} — recognising it isn't the hard part here.`
  }
}

/** Whether the mark scheme typically chains, phrased for a student. */
export function chainClaim(p: SkillExamProfile): string | null {
  if (p.chainedPct < 25) return null
  const how = p.chainedPct >= 60 ? 'usually' : 'often'
  return `The marks ${how} chain, so a wrong first step can block credit on everything after it.`
}

/** Calculator split, phrased. Null when there is no clear lean. */
export function calcClaim(p: SkillExamProfile): string | null {
  const calc = p.calc.calc ?? 0
  const non = p.calc.non_calc ?? 0
  const total = calc + non
  if (total < 3) return null
  if (calc / total >= 0.75) return 'Nearly always on a calculator paper.'
  if (non / total >= 0.75) return 'Nearly always on a non-calculator paper.'
  return 'Appears on both calculator and non-calculator papers.'
}

/** Framing counts as sorted display rows, excluding `bare`. */
export function dressedFramings(p: SkillExamProfile): { key: string; label: string; count: number }[] {
  return Object.entries(p.framing)
    .filter(([k]) => k !== 'bare')
    .sort((a, b) => b[1] - a[1])
    .map(([key, count]) => ({ key, label: FRAMING_LABELS[key] ?? key, count }))
}
