// GENERATED by scripts/build-mark-evidence.ts — do not edit by hand.
// Source: data/exam-audit/ (60 papers, 1758 parts,
// 3955 marks). Re-run the script after coding
// a new paper series.

export type MarkStats = { n: number; mean: number; min: number; max: number; splits: string[] }

/** Marks per part for real exam parts, keyed `${skillId}|${kind}`. */
export const BY_SKILL_KIND: Record<string, MarkStats> = {
 "adding_and_subtracting_fractions|exam": {
  "n": 7,
  "mean": 3.29,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1 A1",
   "M1 M1 C1"
  ]
 },
 "adding_and_subtracting_fractions|mastery": {
  "n": 8,
  "mean": 1.75,
  "min": 1,
  "max": 2,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "algebraic_fractions|exam": {
  "n": 8,
  "mean": 3.88,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1 A1",
   "M1 M1dep A1"
  ]
 },
 "algebraic_fractions|mastery": {
  "n": 8,
  "mean": 2.75,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B1"
  ]
 },
 "algebraic_proof|exam": {
  "n": 7,
  "mean": 3.43,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep C1",
   "M1 A1"
  ]
 },
 "algebraic_proof|mastery": {
  "n": 3,
  "mean": 3.67,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "B1 B1 B1 (one per case examined)"
  ]
 },
 "alternate_and_corresponding_angles|exam": {
  "n": 8,
  "mean": 3.75,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1 C1",
   "M1 A1 C1"
  ]
 },
 "alternate_and_corresponding_angles|mastery": {
  "n": 3,
  "mean": 2.67,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "B2 (B1 a correct angle on the diagram)"
  ]
 },
 "angles_in_polygons|exam": {
  "n": 5,
  "mean": 3.8,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1 C1",
   "P1 P1 P1 A1"
  ]
 },
 "angles_in_polygons|mastery": {
  "n": 9,
  "mean": 2.11,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1 (tick: less than part (a))"
  ]
 },
 "angles_on_lines_and_circles|exam": {
  "n": 3,
  "mean": 3.67,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1 M1 M1dep A1dep",
   "B2 (B1 a correct share step or the angle sum)"
  ]
 },
 "angles_on_lines_and_circles|mastery": {
  "n": 14,
  "mean": 2.5,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B1"
  ]
 },
 "area_and_volume_scale_factors|exam": {
  "n": 4,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep M1dep A1",
   "P1 P1 A1"
  ]
 },
 "area_and_volume_scale_factors|mastery": {
  "n": 5,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "B2 (B1 tick alone)",
   "P1 P1 P1dep A1"
  ]
 },
 "area_of_a_circle|exam": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "area_of_a_circle|mastery": {
  "n": 8,
  "mean": 3.13,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1",
   "M1 A1 M1 A1 A1"
  ]
 },
 "area_of_a_trapezium|exam": {
  "n": 5,
  "mean": 3.2,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1dep",
   "P1 P1 A1"
  ]
 },
 "area_of_parallelograms|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M3 A1"
  ]
 },
 "area_of_parallelograms|mastery": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1"
  ]
 },
 "area_of_triangle_sine|exam": {
  "n": 4,
  "mean": 4.5,
  "min": 4,
  "max": 6,
  "splits": [
   "M1 M1dep M1dep A1",
   "P1 P1 P1 A1"
  ]
 },
 "area_of_triangle_sine|mastery": {
  "n": 1,
  "mean": 5,
  "min": 5,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1 A1"
  ]
 },
 "areas_of_compound_shapes|exam": {
  "n": 3,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "P1 P1 P1 A1",
   "B4"
  ]
 },
 "areas_of_compound_shapes|mastery": {
  "n": 3,
  "mean": 1.33,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 (either order)"
  ]
 },
 "areas_of_squares_and_rectangles|exam": {
  "n": 12,
  "mean": 3.75,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1 A1"
  ]
 },
 "areas_of_squares_and_rectangles|mastery": {
  "n": 7,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B2 (B1 tick alone)",
   "M1 M1 A1"
  ]
 },
 "areas_of_triangles|exam": {
  "n": 10,
  "mean": 4.1,
  "min": 3,
  "max": 6,
  "splits": [
   "P1 P1dep P1 P1 A1",
   "M1 M1 A1dep"
  ]
 },
 "areas_of_triangles|mastery": {
  "n": 4,
  "mean": 2.5,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B4 (B1 per correct row)"
  ]
 },
 "bearings|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep A1 A1ft"
  ]
 },
 "bearings|mastery": {
  "n": 5,
  "mean": 1.2,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 (compass direction or 3-figure bearing)"
  ]
 },
 "box_plots|exam": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "box_plots|mastery": {
  "n": 9,
  "mean": 2.33,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1 A1"
  ]
 },
 "calculating_simple_probability|exam": {
  "n": 4,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "P1 P1 P1 A1",
   "P1 A1"
  ]
 },
 "calculating_simple_probability|mastery": {
  "n": 39,
  "mean": 1.77,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "circle_theorem_alternate_segment|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "B4 angle-chase proof that GD bisects angle ADF (B1-B3 partial)",
   "B1 B1 B1dep"
  ]
 },
 "circle_theorem_alternate_segment|mastery": {
  "n": 2,
  "mean": 2.5,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1 M1 C1",
   "B1 (No + valid statement)"
  ]
 },
 "circle_theorem_angle_at_centre|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 (B1 per correct reasoned statement plus the congruence condition)"
  ]
 },
 "circle_theorem_angle_at_centre|mastery": {
  "n": 5,
  "mean": 2.2,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B1 (tick: greater than part (a))"
  ]
 },
 "circle_theorem_cyclic_quadrilateral|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "circle_theorem_cyclic_quadrilateral|mastery": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M3 chain of angles + A1 (13:17)",
   "B1 B1 B1"
  ]
 },
 "circle_theorem_tangent|exam": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "C1 C1 C1 C1dep",
   "M1 M1 M1dep A1"
  ]
 },
 "circle_theorem_tangent|mastery": {
  "n": 3,
  "mean": 3.33,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 M1 C1"
  ]
 },
 "circumfrence_of_a_circle|exam": {
  "n": 3,
  "mean": 3.67,
  "min": 3,
  "max": 4,
  "splits": [
   "P1 P1 P1 C1",
   "M1 M1 M1dep A1"
  ]
 },
 "circumfrence_of_a_circle|mastery": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "combined_events|exam": {
  "n": 3,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 M1dep A1"
  ]
 },
 "combined_events|mastery": {
  "n": 12,
  "mean": 2.42,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "completing_the_square|exam": {
  "n": 4,
  "mean": 3.25,
  "min": 2,
  "max": 5,
  "splits": [
   "B1 M1 M1dep B1 C1",
   "M1 A1 B1"
  ]
 },
 "completing_the_square|mastery": {
  "n": 9,
  "mean": 2.22,
  "min": 1,
  "max": 3,
  "splits": [
   "P1 P1 A1",
   "B2 (B1 correct bracket with wrong constant)"
  ]
 },
 "composite_functions|exam": {
  "n": 3,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "B1 B1 B1 B1"
  ]
 },
 "composite_functions|mastery": {
  "n": 4,
  "mean": 2.5,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "M2 B2"
  ]
 },
 "compound_units|exam": {
  "n": 28,
  "mean": 3.64,
  "min": 2,
  "max": 6,
  "splits": [
   "M1 M1 M1dep A1",
   "P1 P1 P1 A1"
  ]
 },
 "compound_units|mastery": {
  "n": 27,
  "mean": 2.67,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "conditional_probability|exam": {
  "n": 5,
  "mean": 4,
  "min": 1,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1 A1",
   "M1 M1dep M1dep M1 A1"
  ]
 },
 "conditional_probability|mastery": {
  "n": 7,
  "mean": 2.29,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1dep",
   "M1 M1 A1 A1ft"
  ]
 },
 "congruence_and_similarity|exam": {
  "n": 4,
  "mean": 3.75,
  "min": 3,
  "max": 4,
  "splits": [
   "C1 C1 C1 C1dep",
   "P1 P1 A1"
  ]
 },
 "congruence_and_similarity|mastery": {
  "n": 16,
  "mean": 1.81,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "constructions|mastery": {
  "n": 9,
  "mean": 2.44,
  "min": 1,
  "max": 4,
  "splits": [
   "B2",
   "C1 C1 C1"
  ]
 },
 "converting_decimals_to_fractions|mastery": {
  "n": 4,
  "mean": 1.25,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "converting_fractions_to_decimals|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "converting_fractions_to_decimals|mastery": {
  "n": 6,
  "mean": 1.67,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B3 (B1 per correct match)"
  ]
 },
 "converting_measurements|exam": {
  "n": 15,
  "mean": 3.2,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M2 A1"
  ]
 },
 "converting_measurements|mastery": {
  "n": 30,
  "mean": 1.87,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "coordinates|exam": {
  "n": 3,
  "mean": 3.67,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M2 B1 M1 A1"
  ]
 },
 "coordinates|mastery": {
  "n": 33,
  "mean": 1.79,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "cosine_rule|exam": {
  "n": 3,
  "mean": 4.67,
  "min": 4,
  "max": 6,
  "splits": [
   "P1 P1 P1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "cosine_rule|mastery": {
  "n": 4,
  "mean": 2.75,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1 M1 M1dep A1"
  ]
 },
 "counting_without_listing|mastery": {
  "n": 5,
  "mean": 2.2,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 M1 A1"
  ]
 },
 "cumulative_frequency|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 C1",
   "B1ft median + B1ft compare + B1ft IQR + B1ft compare"
  ]
 },
 "cumulative_frequency|mastery": {
  "n": 11,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "decimals|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 A1 B1ft"
  ]
 },
 "decimals|mastery": {
  "n": 23,
  "mean": 1.48,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 A1 A1ft"
  ]
 },
 "difference_of_two_squares|exam": {
  "n": 4,
  "mean": 3.5,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1 A1",
   "M1 A1"
  ]
 },
 "difference_of_two_squares|mastery": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "direct_proportion|exam": {
  "n": 1,
  "mean": 5,
  "min": 5,
  "max": 5,
  "splits": [
   "M1 M1dep A1 M1 A1ft"
  ]
 },
 "direct_proportion|mastery": {
  "n": 6,
  "mean": 1.5,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "C1"
  ]
 },
 "dividing_fractions|exam": {
  "n": 6,
  "mean": 3.5,
  "min": 2,
  "max": 6,
  "splits": [
   "M1 M1 A1",
   "M1 M1 A1 A1ft"
  ]
 },
 "dividing_fractions|mastery": {
  "n": 7,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "C1",
   "M1 M1dep C1"
  ]
 },
 "enlargements|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 B1 B1 (name, angle or scale factor, centre)"
  ]
 },
 "enlargements|mastery": {
  "n": 7,
  "mean": 2.43,
  "min": 1,
  "max": 3,
  "splits": [
   "B2",
   "B1 B1 B1 (name, scale factor, centre)"
  ]
 },
 "equation_of_a_circle|exam": {
  "n": 3,
  "mean": 4.67,
  "min": 4,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1dep A1",
   "P1 P1 P1dep A1"
  ]
 },
 "equation_of_a_circle|mastery": {
  "n": 3,
  "mean": 1.33,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "M1 radius from diameter + A1 (x^2+y^2=324)"
  ]
 },
 "equations_and_identities|mastery": {
  "n": 7,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B2 (B1 one value correct)"
  ]
 },
 "estimating|exam": {
  "n": 5,
  "mean": 2.6,
  "min": 1,
  "max": 3,
  "splits": [
   "P1 P1dep A1",
   "B1"
  ]
 },
 "estimating|mastery": {
  "n": 17,
  "mean": 1.76,
  "min": 1,
  "max": 5,
  "splits": [
   "C1",
   "M1 A1"
  ]
 },
 "exact_calculations|mastery": {
  "n": 5,
  "mean": 2.4,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1",
   "M2 A1"
  ]
 },
 "exact_trig_values|exam": {
  "n": 5,
  "mean": 4.2,
  "min": 3,
  "max": 7,
  "splits": [
   "P1 P1 P1 C1",
   "M1 M1 A1"
  ]
 },
 "exact_trig_values|mastery": {
  "n": 5,
  "mean": 2,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1dep M1dep A1"
  ]
 },
 "expanding_brackets|mastery": {
  "n": 12,
  "mean": 2.33,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "B2 (B1 one bracket expanded correctly)"
  ]
 },
 "expanding_double_brackets|exam": {
  "n": 5,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep M1 A1",
   "P1 P1 P1 P1dep A1"
  ]
 },
 "expanding_double_brackets|mastery": {
  "n": 10,
  "mean": 3.1,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 A1"
  ]
 },
 "expected_outcomes|exam": {
  "n": 3,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "P1 P1 A1",
   "M1 M1dep A1ft"
  ]
 },
 "expected_outcomes|mastery": {
  "n": 10,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "C1"
  ]
 },
 "exponential_graphs|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B1 M2 A1"
  ]
 },
 "exponential_graphs|mastery": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "B1 B1"
  ]
 },
 "exterior_angles|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B1 M1 M1 A1"
  ]
 },
 "factorising_quadratics|mastery": {
  "n": 9,
  "mean": 1.78,
  "min": 1,
  "max": 2,
  "splits": [
   "B2 (B1 a correct bracket pair form)",
   "M1 A1"
  ]
 },
 "factorising|exam": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1"
  ]
 },
 "factorising|mastery": {
  "n": 13,
  "mean": 1.69,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B1 (circle one of four)"
  ]
 },
 "factors_and_multiples|mastery": {
  "n": 23,
  "mean": 1.78,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B3 (B2 four of five conditions, B1 three)"
  ]
 },
 "finding_the_nth_term|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 B2"
  ]
 },
 "finding_the_nth_term|mastery": {
  "n": 8,
  "mean": 2.38,
  "min": 1,
  "max": 4,
  "splits": [
   "B2",
   "M1 A2 (A1 for correct coefficient with wrong constant)"
  ]
 },
 "forming_expressions_and_formulae|exam": {
  "n": 9,
  "mean": 3.89,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 A1 C1",
   "M1 M1 M1dep M1dep A1"
  ]
 },
 "forming_expressions_and_formulae|mastery": {
  "n": 12,
  "mean": 2.08,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "fractional_and_negative_indices|exam": {
  "n": 4,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M2 B1",
   "M1 A1"
  ]
 },
 "fractional_and_negative_indices|mastery": {
  "n": 9,
  "mean": 2.11,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1 (circle one of four)"
  ]
 },
 "fractional_enlargements|mastery": {
  "n": 8,
  "mean": 2.38,
  "min": 1,
  "max": 3,
  "splits": [
   "B2",
   "B1 B1 B1 (name, scale factor, centre)"
  ]
 },
 "fractions_decimals_and_percentages|exam": {
  "n": 8,
  "mean": 3.25,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "B1 M1 A1"
  ]
 },
 "fractions_decimals_and_percentages|mastery": {
  "n": 31,
  "mean": 2.03,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "fractions_of_amounts|exam": {
  "n": 9,
  "mean": 4.22,
  "min": 3,
  "max": 6,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 M1 M1dep A1"
  ]
 },
 "fractions_of_amounts|mastery": {
  "n": 34,
  "mean": 3.26,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "P1 P1 P1 P1 A1"
  ]
 },
 "frequency_diagrams|mastery": {
  "n": 2,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "B2"
  ]
 },
 "frequency_trees|exam": {
  "n": 7,
  "mean": 3.14,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1 B1 B1ft",
   "B1 B1 B1ft"
  ]
 },
 "frequency_trees|mastery": {
  "n": 5,
  "mean": 3.4,
  "min": 2,
  "max": 5,
  "splits": [
   "B1 B1 B1ft B1ft B1ft",
   "B1 B1 B1ft B1ft"
  ]
 },
 "function_machines|mastery": {
  "n": 23,
  "mean": 1.48,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "functions_notation|exam": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "functions_notation|mastery": {
  "n": 3,
  "mean": 1.67,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "M1 A1 (and No)"
  ]
 },
 "gathering_and_organising_data|mastery": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B3",
   "C3"
  ]
 },
 "gradient_of_a_curve|mastery": {
  "n": 3,
  "mean": 2.33,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "B1 B2dep"
  ]
 },
 "graph_transformations|exam": {
  "n": 2,
  "mean": 2.5,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 M1 A1",
   "B2 (7,8), B1 per coordinate"
  ]
 },
 "graph_transformations|mastery": {
  "n": 14,
  "mean": 1.36,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B1 (mark intention)"
  ]
 },
 "grouped_frequency_tables|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "M1 M1 M1 A1"
  ]
 },
 "grouped_frequency_tables|mastery": {
  "n": 12,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B2"
  ]
 },
 "growth_and_decay|exam": {
  "n": 4,
  "mean": 3.75,
  "min": 3,
  "max": 4,
  "splits": [
   "P1 P1 P1 A1",
   "M1 M1dep A1"
  ]
 },
 "growth_and_decay|mastery": {
  "n": 17,
  "mean": 3,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "M1 M1dep A1"
  ]
 },
 "highest_common_factor|mastery": {
  "n": 6,
  "mean": 1.83,
  "min": 1,
  "max": 2,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "histograms|mastery": {
  "n": 9,
  "mean": 3.22,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "B3"
  ]
 },
 "indices|exam": {
  "n": 4,
  "mean": 2.75,
  "min": 2,
  "max": 3,
  "splits": [
   "B3 (constraint-graded)",
   "M1 A1 A1"
  ]
 },
 "indices|mastery": {
  "n": 47,
  "mean": 1.64,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "inequalities|exam": {
  "n": 3,
  "mean": 3.67,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 C1",
   "B4 (B1 per correct line, final mark for the region)"
  ]
 },
 "inequalities|mastery": {
  "n": 18,
  "mean": 2,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "interquartile_range|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B1ft median + B1ft compare + B1ft IQR + B1ft compare"
  ]
 },
 "interquartile_range|mastery": {
  "n": 7,
  "mean": 2.57,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "M1 M1 A1"
  ]
 },
 "inverse_functions|exam": {
  "n": 2,
  "mean": 4.5,
  "min": 4,
  "max": 5,
  "splits": [
   "B1 B1 B1 B1",
   "M1 M1 M1dep M1dep A1"
  ]
 },
 "inverse_functions|mastery": {
  "n": 3,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1",
   "B1 A1"
  ]
 },
 "inverse_proportion|exam": {
  "n": 2,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1 M1 A1ft",
   "M1 B1 A1"
  ]
 },
 "inverse_proportion|mastery": {
  "n": 15,
  "mean": 1.53,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1 (a correct point substituted with a verdict)"
  ]
 },
 "irregular_and_improper_fractions|exam": {
  "n": 3,
  "mean": 3.33,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1 A1ft",
   "M1 A1 B1ft"
  ]
 },
 "irregular_and_improper_fractions|mastery": {
  "n": 10,
  "mean": 1.5,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "C1"
  ]
 },
 "iteration|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "iteration|mastery": {
  "n": 4,
  "mean": 2.25,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 B1ft",
   "B1 (a converged value above the stated bound)"
  ]
 },
 "kinematic_graphs|exam": {
  "n": 3,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 interval read + M1dep gradient + A1",
   "B1 B1ft B1ft"
  ]
 },
 "kinematic_graphs|mastery": {
  "n": 19,
  "mean": 1.89,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "lengths_and_perimeters|exam": {
  "n": 7,
  "mean": 3.57,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1",
   "M2 M1 A1"
  ]
 },
 "lengths_and_perimeters|mastery": {
  "n": 7,
  "mean": 2.14,
  "min": 1,
  "max": 4,
  "splits": [
   "P1 P1 P1 A1",
   "P1 P1 A1"
  ]
 },
 "loci|mastery": {
  "n": 4,
  "mean": 3.25,
  "min": 3,
  "max": 4,
  "splits": [
   "C1 C1 C1",
   "B4 (B1 per correct construction, final mark for the region)"
  ]
 },
 "lowest_common_multiple|exam": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "B1 A1"
  ]
 },
 "lowest_common_multiple|mastery": {
  "n": 7,
  "mean": 1.43,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "mean|exam": {
  "n": 7,
  "mean": 4.29,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1 M1dep M1dep A1",
   "M1 M1 M1dep A1"
  ]
 },
 "mean|mastery": {
  "n": 18,
  "mean": 2.5,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "measuring_lines_and_angles|mastery": {
  "n": 13,
  "mean": 1.15,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B1 (range [54, 58])"
  ]
 },
 "median|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "B3 (B1 per condition met)",
   "B1ft median + B1ft compare + B1ft IQR + B1ft compare"
  ]
 },
 "median|mastery": {
  "n": 17,
  "mean": 2.06,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B1 C1 B1 C1"
  ]
 },
 "mode|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B3 (B1 per condition met)"
  ]
 },
 "mode|mastery": {
  "n": 5,
  "mean": 1.6,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "C1"
  ]
 },
 "mutually_exclusive_events|exam": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "P1 P1 A1"
  ]
 },
 "mutually_exclusive_events|mastery": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "nth_term_quadratic_sequences|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 (n-15)^2 + M1dep +11 form + A1 explanation"
  ]
 },
 "nth_term_quadratic_sequences|mastery": {
  "n": 3,
  "mean": 3.33,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "parts_of_a_circle|mastery": {
  "n": 12,
  "mean": 1.33,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B1 B1 (name two regions)"
  ]
 },
 "percentage_change|exam": {
  "n": 9,
  "mean": 4.67,
  "min": 4,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1 A1",
   "M1 M1 M1 M1dep A1"
  ]
 },
 "percentage_change|mastery": {
  "n": 19,
  "mean": 3.11,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "P1 P1 P1 C1"
  ]
 },
 "perpendicular_gradients|exam": {
  "n": 4,
  "mean": 4.5,
  "min": 4,
  "max": 5,
  "splits": [
   "P1 P1 P1dep A1",
   "P1 P1 P1 P1dep A1"
  ]
 },
 "perpendicular_gradients|mastery": {
  "n": 5,
  "mean": 3.4,
  "min": 1,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1dep A1",
   "M1 M1 M1dep M1dep A1"
  ]
 },
 "pie_charts|exam": {
  "n": 4,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 M1"
  ]
 },
 "pie_charts|mastery": {
  "n": 16,
  "mean": 2.19,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B1"
  ]
 },
 "plans_and_elevations|exam": {
  "n": 2,
  "mean": 2.5,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1 A1",
   "M1 A1"
  ]
 },
 "plans_and_elevations|mastery": {
  "n": 10,
  "mean": 1.9,
  "min": 1,
  "max": 3,
  "splits": [
   "C1",
   "M1 A1"
  ]
 },
 "plotting_straight_line_graphs|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 (B1 per correct line, final mark for the region)"
  ]
 },
 "plotting_straight_line_graphs|mastery": {
  "n": 6,
  "mean": 2.5,
  "min": 2,
  "max": 3,
  "splits": [
   "B2",
   "M1 M1 A1"
  ]
 },
 "prime_factor_decomposition|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B3"
  ]
 },
 "prime_factor_decomposition|mastery": {
  "n": 9,
  "mean": 2.22,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B3 (B2 four of five conditions, B1 three)"
  ]
 },
 "probability_spaces|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1ft"
  ]
 },
 "probability_spaces|mastery": {
  "n": 10,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B2"
  ]
 },
 "properties_of_2d_shapes|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1 A1"
  ]
 },
 "properties_of_2d_shapes|mastery": {
  "n": 8,
  "mean": 1.13,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 B1dep"
  ]
 },
 "properties_of_3d_solids|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1"
  ]
 },
 "properties_of_3d_solids|mastery": {
  "n": 11,
  "mean": 1.27,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (B1 tick alone)"
  ]
 },
 "proportion_with_powers|exam": {
  "n": 4,
  "mean": 3.5,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep M1dep A1",
   "M1 M1dep A1 M1 A1ft"
  ]
 },
 "proportion_with_powers|mastery": {
  "n": 7,
  "mean": 2.29,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "M1 M1 A1"
  ]
 },
 "proportion|exam": {
  "n": 26,
  "mean": 3.58,
  "min": 2,
  "max": 5,
  "splits": [
   "P1 P1 P1 A1",
   "M1 M1dep M1 A1"
  ]
 },
 "proportion|mastery": {
  "n": 39,
  "mean": 2.51,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1",
   "M1 M1dep A1"
  ]
 },
 "pythagoras_theorem|exam": {
  "n": 6,
  "mean": 4.5,
  "min": 4,
  "max": 5,
  "splits": [
   "P1 P1dep P1 P1 A1",
   "P1 P1dep P1 A1"
  ]
 },
 "pythagoras_theorem|mastery": {
  "n": 11,
  "mean": 2.82,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "quadratic_functions|mastery": {
  "n": 26,
  "mean": 2.08,
  "min": 1,
  "max": 3,
  "splits": [
   "B2",
   "M1 A1"
  ]
 },
 "quadratic_inequalities|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B1 M1 A1ft B1ft"
  ]
 },
 "quadratic_inequalities|mastery": {
  "n": 4,
  "mean": 1.75,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1 (identify the error)"
  ]
 },
 "range|exam": {
  "n": 2,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "B3 (B1 per condition met)",
   "M1 M1 M1 M1 A1"
  ]
 },
 "range|mastery": {
  "n": 14,
  "mean": 2.29,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "ratio|exam": {
  "n": 32,
  "mean": 3.38,
  "min": 2,
  "max": 6,
  "splits": [
   "M1 M1dep A1",
   "P1 A1"
  ]
 },
 "ratio|mastery": {
  "n": 54,
  "mean": 2.59,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "rearranging_formulae|exam": {
  "n": 3,
  "mean": 3.33,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "rearranging_formulae|mastery": {
  "n": 10,
  "mean": 2.6,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "reciprocals|mastery": {
  "n": 4,
  "mean": 1.25,
  "min": 1,
  "max": 2,
  "splits": [
   "B1 (circle one of four)",
   "B1"
  ]
 },
 "recurring_decimals_to_fractions|exam": {
  "n": 3,
  "mean": 3.67,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1 C1",
   "M1 M1dep A1"
  ]
 },
 "recurring_decimals_to_fractions|mastery": {
  "n": 7,
  "mean": 2.57,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep C1"
  ]
 },
 "reflections|mastery": {
  "n": 10,
  "mean": 1.3,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2"
  ]
 },
 "relative_frequency|exam": {
  "n": 2,
  "mean": 2.5,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 M1 A1"
  ]
 },
 "relative_frequency|mastery": {
  "n": 12,
  "mean": 1.58,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1 (choice + valid reason)"
  ]
 },
 "reverse_percentage|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "reverse_percentage|mastery": {
  "n": 11,
  "mean": 2.82,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "rotations|exam": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 A2",
   "B1 B1 B1 (name, angle or scale factor, centre)"
  ]
 },
 "rotations|mastery": {
  "n": 5,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "B2",
   "B2 (B1 angle or centre alone)"
  ]
 },
 "rounding|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 B2"
  ]
 },
 "rounding|mastery": {
  "n": 7,
  "mean": 1.43,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 B1 (pick from list of 4)"
  ]
 },
 "sampling|mastery": {
  "n": 7,
  "mean": 1.29,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "P1 P1 A1"
  ]
 },
 "scatter_graphs|exam": {
  "n": 5,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1ft",
   "B1 M1 A1"
  ]
 },
 "scatter_graphs|mastery": {
  "n": 20,
  "mean": 1.25,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "C1"
  ]
 },
 "sector_calculations|exam": {
  "n": 2,
  "mean": 6.5,
  "min": 6,
  "max": 7,
  "splits": [
   "M2 M2 M1 A1",
   "M1 M1 A1 B1 M2 A1"
  ]
 },
 "sector_calculations|mastery": {
  "n": 10,
  "mean": 3.1,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "B1 (tick: smaller than part (a))"
  ]
 },
 "sequences|exam": {
  "n": 6,
  "mean": 3,
  "min": 2,
  "max": 5,
  "splits": [
   "B1 B1ft B1",
   "P1 A1"
  ]
 },
 "sequences|mastery": {
  "n": 29,
  "mean": 1.55,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1dep M1dep A1"
  ]
 },
 "significant_figures|mastery": {
  "n": 4,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "simple_arithmetic|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1 A1"
  ]
 },
 "simple_arithmetic|mastery": {
  "n": 102,
  "mean": 2.41,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "simple_charts|exam": {
  "n": 2,
  "mean": 2.5,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 M1dep A1"
  ]
 },
 "simple_charts|mastery": {
  "n": 25,
  "mean": 2.2,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "simplifying_expressions|exam": {
  "n": 6,
  "mean": 2.83,
  "min": 2,
  "max": 3,
  "splits": [
   "B1 B1ft B1",
   "B3 (match algebra to description)"
  ]
 },
 "simplifying_expressions|mastery": {
  "n": 30,
  "mean": 1.87,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "simplifying_fractions|exam": {
  "n": 3,
  "mean": 2.67,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 A1 B1ft"
  ]
 },
 "simplifying_fractions|mastery": {
  "n": 6,
  "mean": 2.17,
  "min": 1,
  "max": 4,
  "splits": [
   "B2 (B1 an unsimplified equivalent)",
   "M1 A1 B1ft"
  ]
 },
 "simplifying_indices|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 each of three simplified terms"
  ]
 },
 "simplifying_indices|mastery": {
  "n": 24,
  "mean": 1.83,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B2"
  ]
 },
 "simplifying_ratio|exam": {
  "n": 7,
  "mean": 3.14,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 A1ft"
  ]
 },
 "simplifying_ratio|mastery": {
  "n": 13,
  "mean": 2.08,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "simultaneous_equations_quadratic|exam": {
  "n": 4,
  "mean": 5,
  "min": 4,
  "max": 6,
  "splits": [
   "P1 P1 P1 P1 A1",
   "M1 M1 M1 A1"
  ]
 },
 "simultaneous_equations|exam": {
  "n": 2,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 M1 M1 A1"
  ]
 },
 "simultaneous_equations|mastery": {
  "n": 10,
  "mean": 3.7,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 A1 M1dep A1"
  ]
 },
 "sine_rule|exam": {
  "n": 3,
  "mean": 4.33,
  "min": 3,
  "max": 6,
  "splits": [
   "M1 M1 A1",
   "M1 M1dep A1 A1ft"
  ]
 },
 "sine_rule|mastery": {
  "n": 4,
  "mean": 3.25,
  "min": 2,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1 A1",
   "M1 M1dep A1"
  ]
 },
 "sketching_functions|exam": {
  "n": 1,
  "mean": 5,
  "min": 5,
  "max": 5,
  "splits": [
   "B1 M1 M1dep B1 C1"
  ]
 },
 "sketching_functions|mastery": {
  "n": 14,
  "mean": 1.71,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B2 (B1 per valid criticism)"
  ]
 },
 "solving_linear_equations|exam": {
  "n": 27,
  "mean": 3.89,
  "min": 2,
  "max": 5,
  "splits": [
   "P1 P1 P1 A1",
   "M2 M1 A1"
  ]
 },
 "solving_linear_equations|mastery": {
  "n": 31,
  "mean": 2.03,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "solving_quadratic_equations_factorising|exam": {
  "n": 13,
  "mean": 4.77,
  "min": 4,
  "max": 6,
  "splits": [
   "M1 M1dep M1 A1",
   "P1 P1 P1 P1 A1"
  ]
 },
 "solving_quadratic_equations_factorising|mastery": {
  "n": 5,
  "mean": 2.8,
  "min": 1,
  "max": 4,
  "splits": [
   "M2 B1ft",
   "M1 M1 A1"
  ]
 },
 "solving_quadratic_equations_quadratic_equation|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1 A1"
  ]
 },
 "solving_quadratic_equations_quadratic_equation|mastery": {
  "n": 4,
  "mean": 3.25,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 expand + M1dep equation + M1dep rearrange + A1 d,e,f"
  ]
 },
 "standard_form|exam": {
  "n": 7,
  "mean": 3,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 A1ft",
   "M2 B1"
  ]
 },
 "standard_form|mastery": {
  "n": 23,
  "mean": 1.52,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "substitution|mastery": {
  "n": 36,
  "mean": 2.11,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B2"
  ]
 },
 "surds_expanding_and_rationalising|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M2 A1 (M1 one or two correct exact values)"
  ]
 },
 "surds_expanding_and_rationalising|mastery": {
  "n": 7,
  "mean": 2.71,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "surds_simplifying|exam": {
  "n": 4,
  "mean": 4,
  "min": 2,
  "max": 7,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 A1"
  ]
 },
 "surds_simplifying|mastery": {
  "n": 7,
  "mean": 2.86,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1",
   "M1indep M1 M1dep A1"
  ]
 },
 "surface_area_of_a_cone|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "P1 P1dep P1 A1"
  ]
 },
 "surface_area_of_a_cone|mastery": {
  "n": 2,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1 (identify error)",
   "B1"
  ]
 },
 "surface_area_of_a_cylinder|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "surface_area_of_a_sphere|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "symmetry|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4"
  ]
 },
 "symmetry|mastery": {
  "n": 7,
  "mean": 1.43,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (shade for 2 lines symmetry)"
  ]
 },
 "systematic_listing|exam": {
  "n": 4,
  "mean": 3.5,
  "min": 2,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1 A1",
   "B3 (constraint-graded)"
  ]
 },
 "systematic_listing|mastery": {
  "n": 11,
  "mean": 1.82,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1ft"
  ]
 },
 "time_calculations|exam": {
  "n": 7,
  "mean": 4,
  "min": 2,
  "max": 6,
  "splits": [
   "M2 M2 M1dep A1",
   "P1 P1 C1"
  ]
 },
 "time_calculations|mastery": {
  "n": 15,
  "mean": 1.93,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "time_series|exam": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 M1 A1ft"
  ]
 },
 "time_series|mastery": {
  "n": 10,
  "mean": 1.6,
  "min": 1,
  "max": 2,
  "splits": [
   "M1 A1",
   "B2 (B1 at least four points correct)"
  ]
 },
 "translations|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 A2"
  ]
 },
 "translations|mastery": {
  "n": 7,
  "mean": 1.57,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (B1 one component correct or a described translation)"
  ]
 },
 "tree_diagrams|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M2 M1 A1"
  ]
 },
 "tree_diagrams|mastery": {
  "n": 23,
  "mean": 2.09,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1 B1"
  ]
 },
 "trig_graphs|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1 A1"
  ]
 },
 "trig_graphs|mastery": {
  "n": 7,
  "mean": 1.57,
  "min": 1,
  "max": 2,
  "splits": [
   "M1 A1",
   "B1 (tick one of four)"
  ]
 },
 "trigonometry_3d|mastery": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "P1 P1 A1",
   "M1 M1dep A1"
  ]
 },
 "trigonometry_missing_angles|mastery": {
  "n": 4,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "trigonometry_missing_sides|exam": {
  "n": 3,
  "mean": 5,
  "min": 3,
  "max": 6,
  "splits": [
   "B1 M2 M2dep A1",
   "B1 P1 A1"
  ]
 },
 "trigonometry_missing_sides|mastery": {
  "n": 12,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "understanding_straight_line_graphs|exam": {
  "n": 4,
  "mean": 3.75,
  "min": 3,
  "max": 5,
  "splits": [
   "P1 P1 P1 P1dep A1",
   "M1 M1 C1"
  ]
 },
 "understanding_straight_line_graphs|mastery": {
  "n": 32,
  "mean": 2.09,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 M1 A1"
  ]
 },
 "upper_and_lower_bounds|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "B1 M1 A1",
   "M1 B2 A1"
  ]
 },
 "upper_and_lower_bounds|mastery": {
  "n": 25,
  "mean": 2.16,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "B2 (B1 one bound in the correct position)"
  ]
 },
 "vector_proof|exam": {
  "n": 2,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "B5 (banded B1-B4 by which correct vectors are stated)",
   "M1 M1dep A1"
  ]
 },
 "vector_proof|mastery": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "P1 P1 P1 A1",
   "M1 one expr + M1dep two exprs + A1 simplify + A1 parallel indication"
  ]
 },
 "vectors|exam": {
  "n": 2,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "B5 (banded B1-B4 by which correct vectors are stated)",
   "M1 M1dep A1"
  ]
 },
 "vectors|mastery": {
  "n": 17,
  "mean": 2,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B2 (B1 one component correct or a described translation)"
  ]
 },
 "venn_diagrams|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 (B1 per correct region)"
  ]
 },
 "venn_diagrams|mastery": {
  "n": 26,
  "mean": 1.77,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "volume_of_a_prism|exam": {
  "n": 13,
  "mean": 3.77,
  "min": 2,
  "max": 5,
  "splits": [
   "P1 P1 P1 A1",
   "P1 P1 P1 P1 A1"
  ]
 },
 "volume_of_a_prism|mastery": {
  "n": 8,
  "mean": 2.63,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "volume_of_a_pyramid_and_cone|exam": {
  "n": 2,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "M1 M2 A1"
  ]
 },
 "volume_of_a_pyramid_and_cone|mastery": {
  "n": 4,
  "mean": 2.75,
  "min": 2,
  "max": 3,
  "splits": [
   "M2 A1",
   "P1 P1 A1"
  ]
 },
 "volume_of_a_sphere|exam": {
  "n": 4,
  "mean": 3.75,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 M1dep A1"
  ]
 },
 "volume_of_a_sphere|mastery": {
  "n": 4,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "M1 M1 M1dep A1"
  ]
 }
}

/** Fallback when a skill has too little evidence of its own. */
export const BY_KIND: Record<string, MarkStats> = {
 "mastery": {
  "n": 1508,
  "mean": 2.03,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "exam": {
  "n": 250,
  "mean": 3.59,
  "min": 1,
  "max": 7,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 A1"
  ]
 }
}

/** Last-resort centre: every coded part, regardless of skill or kind. */
export const OVERALL: MarkStats = {
 "n": 1758,
 "mean": 2.25,
 "min": 1,
 "max": 7,
 "splits": []
}

/**
 * Average METHOD marks per part, by the part's mark total.
 *
 * Method marks are what a real scheme awards for a sound approach behind a wrong
 * answer — the credit auto-grading is blind to. Note the 1-mark row: a one-mark
 * part never carries method marks, which is what makes the blind spot bounded.
 *
 * Only part sizes with at least 12 coded parts appear. Sizes above the
 * largest key are held at its rate by methodMarkShare(), so a thinly-sampled
 * large size would set that ceiling from noise.
 */
export const METHOD_SHARE_BY_MARKS: Record<number, number> = {
 "1": 0,
 "2": 0.54,
 "3": 0.95,
 "4": 1.14,
 "5": 1.76
}
