// GENERATED by scripts/build-mark-evidence.ts — do not edit by hand.
// Source: data/exam-audit/ (30 papers, 1095 parts,
// 2400 marks). Re-run the script after coding
// a new paper series.

export type MarkStats = { n: number; mean: number; min: number; max: number; splits: string[] }

/** Marks per part for real exam parts, keyed `${skillId}|${kind}`. */
export const BY_SKILL_KIND: Record<string, MarkStats> = {
 "adding_and_subtracting_fractions|exam": {
  "n": 5,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1 A1",
   "M1 A1 B1ft"
  ]
 },
 "adding_and_subtracting_fractions|mastery": {
  "n": 2,
  "mean": 1.5,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "M1 common denominator + A1 (9/10)"
  ]
 },
 "algebraic_fractions|exam": {
  "n": 5,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 A1 M1 A1ft"
  ]
 },
 "algebraic_fractions|mastery": {
  "n": 6,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 A1"
  ]
 },
 "algebraic_proof|exam": {
  "n": 6,
  "mean": 3.5,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "M1 M1 M1dep A1"
  ]
 },
 "algebraic_proof|mastery": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "B1 B1 B1 (one per case examined)"
  ]
 },
 "alternate_and_corresponding_angles|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 correct equation and solve (B1-B3 partial expressions)"
  ]
 },
 "alternate_and_corresponding_angles|mastery": {
  "n": 3,
  "mean": 2.67,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "B2 (B1 a correct angle on the diagram)"
  ]
 },
 "angles_in_polygons|mastery": {
  "n": 11,
  "mean": 1.91,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "angles_on_lines_and_circles|exam": {
  "n": 2,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "B2 (B1 a correct share step or the angle sum)",
   "M1 equation + M1dep collect + M1dep solve + A1 ratio"
  ]
 },
 "angles_on_lines_and_circles|mastery": {
  "n": 9,
  "mean": 2.89,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 A1 (No + values)"
  ]
 },
 "area_of_a_circle|exam": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "area_of_a_circle|mastery": {
  "n": 7,
  "mean": 3.29,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1 M1 A1 A1",
   "M1 A1 (pi=3)"
  ]
 },
 "area_of_a_trapezium|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep M1 A1",
   "M1 M1dep A1"
  ]
 },
 "area_of_triangle_sine|exam": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1"
  ]
 },
 "areas_of_compound_shapes|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4"
  ]
 },
 "areas_of_compound_shapes|mastery": {
  "n": 3,
  "mean": 1.33,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 (either order)"
  ]
 },
 "areas_of_squares_and_rectangles|exam": {
  "n": 10,
  "mean": 3.8,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1 A1"
  ]
 },
 "areas_of_squares_and_rectangles|mastery": {
  "n": 6,
  "mean": 1.83,
  "min": 1,
  "max": 3,
  "splits": [
   "B2 (B1 tick alone)",
   "M1 M1dep A1"
  ]
 },
 "areas_of_triangles|exam": {
  "n": 3,
  "mean": 3.33,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1 A1ft",
   "M1 M1 A1"
  ]
 },
 "areas_of_triangles|mastery": {
  "n": 4,
  "mean": 2.5,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B4 (B1 per correct row)"
  ]
 },
 "bearings|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep A1 A1ft"
  ]
 },
 "bearings|mastery": {
  "n": 5,
  "mean": 1.2,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 (compass direction or 3-figure bearing)"
  ]
 },
 "box_plots|mastery": {
  "n": 4,
  "mean": 2.75,
  "min": 1,
  "max": 4,
  "splits": [
   "B1 B1 B1ft",
   "B3 (B2/B1 partial plots)"
  ]
 },
 "calculating_simple_probability|mastery": {
  "n": 29,
  "mean": 1.72,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "circle_theorem_alternate_segment|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 angle-chase proof that GD bisects angle ADF (B1-B3 partial)"
  ]
 },
 "circle_theorem_alternate_segment|mastery": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1 (No + valid statement)"
  ]
 },
 "circle_theorem_angle_at_centre|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 (B1 per correct reasoned statement plus the congruence condition)"
  ]
 },
 "circle_theorem_angle_at_centre|mastery": {
  "n": 4,
  "mean": 2,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B1 (tick: greater than part (a))"
  ]
 },
 "circle_theorem_cyclic_quadrilateral|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "circle_theorem_cyclic_quadrilateral|mastery": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M3 chain of angles + A1 (13:17)"
  ]
 },
 "circle_theorem_tangent|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1"
  ]
 },
 "circle_theorem_tangent|mastery": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "circumfrence_of_a_circle|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 M1dep A1"
  ]
 },
 "circumfrence_of_a_circle|mastery": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "combined_events|exam": {
  "n": 3,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 M1dep A1"
  ]
 },
 "combined_events|mastery": {
  "n": 10,
  "mean": 2.4,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "completing_the_square|exam": {
  "n": 3,
  "mean": 2.67,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1 B1",
   "B2 (7,8), B1 per coordinate"
  ]
 },
 "completing_the_square|mastery": {
  "n": 6,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B2 (B1 correct bracket with wrong constant)",
   "M1 M1dep A1"
  ]
 },
 "composite_functions|exam": {
  "n": 3,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "B1 B1 B1 B1"
  ]
 },
 "composite_functions|mastery": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1"
  ]
 },
 "compound_units|exam": {
  "n": 13,
  "mean": 3.46,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 M1dep A1"
  ]
 },
 "compound_units|mastery": {
  "n": 18,
  "mean": 2.89,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "conditional_probability|exam": {
  "n": 2,
  "mean": 4.5,
  "min": 4,
  "max": 5,
  "splits": [
   "M1 M1dep M1dep M1 A1",
   "M1 M1 M1dep A1"
  ]
 },
 "conditional_probability|mastery": {
  "n": 4,
  "mean": 2.25,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1 A1 A1ft",
   "B1ft"
  ]
 },
 "congruence_and_similarity|exam": {
  "n": 4,
  "mean": 4.25,
  "min": 4,
  "max": 5,
  "splits": [
   "M1 M1dep M1dep A1",
   "M1 volume expr + M1dep ratio + M1dep cube-root sf + M1dep edge sum + A1 (150)"
  ]
 },
 "congruence_and_similarity|mastery": {
  "n": 15,
  "mean": 1.67,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "constructions|mastery": {
  "n": 4,
  "mean": 2.5,
  "min": 1,
  "max": 4,
  "splits": [
   "B1 (compasses, not freehand)",
   "B4 (B1 per correct construction, final mark for the region)"
  ]
 },
 "converting_decimals_to_fractions|mastery": {
  "n": 3,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "converting_fractions_to_decimals|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "converting_fractions_to_decimals|mastery": {
  "n": 5,
  "mean": 1.8,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B3 (B1 per correct match)"
  ]
 },
 "converting_measurements|exam": {
  "n": 8,
  "mean": 3.38,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "B1 M2 A1 (M1 correct step using one operator)"
  ]
 },
 "converting_measurements|mastery": {
  "n": 17,
  "mean": 1.88,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "coordinates|exam": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "coordinates|mastery": {
  "n": 24,
  "mean": 1.88,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "cosine_rule|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1"
  ]
 },
 "cosine_rule|mastery": {
  "n": 4,
  "mean": 2.75,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1 M1 M1dep A1"
  ]
 },
 "counting_without_listing|mastery": {
  "n": 3,
  "mean": 2.33,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 M1 A1"
  ]
 },
 "cumulative_frequency|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B1ft median + B1ft compare + B1ft IQR + B1ft compare"
  ]
 },
 "cumulative_frequency|mastery": {
  "n": 6,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 (all four values)",
   "B1ft B1"
  ]
 },
 "decimals|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 A1 B1ft"
  ]
 },
 "decimals|mastery": {
  "n": 13,
  "mean": 1.38,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (B1 a pair satisfying two of the three conditions)"
  ]
 },
 "difference_of_two_squares|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1"
  ]
 },
 "difference_of_two_squares|mastery": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "direct_proportion|exam": {
  "n": 1,
  "mean": 5,
  "min": 5,
  "max": 5,
  "splits": [
   "M1 M1dep A1 M1 A1ft"
  ]
 },
 "direct_proportion|mastery": {
  "n": 3,
  "mean": 1.33,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (B1 partial)"
  ]
 },
 "dividing_fractions|exam": {
  "n": 5,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "M1 M1 A1 A1ft"
  ]
 },
 "dividing_fractions|mastery": {
  "n": 2,
  "mean": 1.5,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "enlargements|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 B1 B1 (name, angle or scale factor, centre)"
  ]
 },
 "enlargements|mastery": {
  "n": 7,
  "mean": 2.57,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 B1 B1 (name, scale factor, centre)",
   "B1 B1 B1 (name + SF + centre)"
  ]
 },
 "equation_of_a_circle|mastery": {
  "n": 3,
  "mean": 1.33,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "M1 radius from diameter + A1 (x^2+y^2=324)"
  ]
 },
 "estimating|exam": {
  "n": 2,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 A1 A1"
  ]
 },
 "estimating|mastery": {
  "n": 9,
  "mean": 1.56,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1 (reason referencing the rounding direction)"
  ]
 },
 "exact_trig_values|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M2 A1 (M1 one or two correct exact values)"
  ]
 },
 "exact_trig_values|mastery": {
  "n": 5,
  "mean": 2,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1dep M1dep A1"
  ]
 },
 "expanding_brackets|mastery": {
  "n": 12,
  "mean": 2.33,
  "min": 1,
  "max": 4,
  "splits": [
   "B2 (B1 one bracket expanded correctly)",
   "B1"
  ]
 },
 "expanding_double_brackets|exam": {
  "n": 4,
  "mean": 3.75,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep M1 A1",
   "M1 M1dep A1"
  ]
 },
 "expanding_double_brackets|mastery": {
  "n": 7,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "expected_outcomes|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1ft"
  ]
 },
 "expected_outcomes|mastery": {
  "n": 6,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 M1dep A1"
  ]
 },
 "factorising_quadratics|mastery": {
  "n": 7,
  "mean": 1.86,
  "min": 1,
  "max": 2,
  "splits": [
   "B2 (B1 a correct bracket pair form)",
   "B2 (B1 brackets with one correct value)"
  ]
 },
 "factorising|mastery": {
  "n": 6,
  "mean": 1.5,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B1 (circle one of four)"
  ]
 },
 "factors_and_multiples|mastery": {
  "n": 16,
  "mean": 1.94,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B3 (B2 four of five conditions, B1 three)"
  ]
 },
 "finding_the_nth_term|mastery": {
  "n": 6,
  "mean": 2.5,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A2 (A1 for correct coefficient with wrong constant)",
   "B2 (B1 correct coefficient with wrong constant)"
  ]
 },
 "forming_expressions_and_formulae|exam": {
  "n": 7,
  "mean": 4.14,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1 M1dep M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "forming_expressions_and_formulae|mastery": {
  "n": 9,
  "mean": 2.22,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B3 (B1 per correct match)"
  ]
 },
 "fractional_and_negative_indices|exam": {
  "n": 2,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "fractional_and_negative_indices|mastery": {
  "n": 6,
  "mean": 1.83,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 (circle one of four)",
   "B1"
  ]
 },
 "fractional_enlargements|mastery": {
  "n": 5,
  "mean": 2.4,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 B1 B1 (name, scale factor, centre)",
   "B1"
  ]
 },
 "fractions_decimals_and_percentages|exam": {
  "n": 4,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 M1dep A1"
  ]
 },
 "fractions_decimals_and_percentages|mastery": {
  "n": 24,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "fractions_of_amounts|exam": {
  "n": 5,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 M1 M1dep A1"
  ]
 },
 "fractions_of_amounts|mastery": {
  "n": 21,
  "mean": 2.9,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1 A1"
  ]
 },
 "frequency_trees|exam": {
  "n": 4,
  "mean": 3.75,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 A1 B1 B1ft",
   "B1 B1 B1ft"
  ]
 },
 "frequency_trees|mastery": {
  "n": 3,
  "mean": 3.67,
  "min": 2,
  "max": 5,
  "splits": [
   "B1 B1 B1ft B1ft B1ft",
   "B1 B1 B1ft B1ft"
  ]
 },
 "function_machines|mastery": {
  "n": 18,
  "mean": 1.39,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B1 (operations)"
  ]
 },
 "functions_notation|exam": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "functions_notation|mastery": {
  "n": 2,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1 (and No)",
   "M1 A1"
  ]
 },
 "graph_transformations|exam": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "B2 (7,8), B1 per coordinate"
  ]
 },
 "graph_transformations|mastery": {
  "n": 11,
  "mean": 1.27,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B1 (mark intention)"
  ]
 },
 "grouped_frequency_tables|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1 A1"
  ]
 },
 "grouped_frequency_tables|mastery": {
  "n": 8,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "B1"
  ]
 },
 "growth_and_decay|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "growth_and_decay|mastery": {
  "n": 10,
  "mean": 2.9,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 A1"
  ]
 },
 "highest_common_factor|mastery": {
  "n": 1,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1"
  ]
 },
 "histograms|mastery": {
  "n": 4,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1 M1dep A1"
  ]
 },
 "indices|exam": {
  "n": 4,
  "mean": 2.75,
  "min": 2,
  "max": 3,
  "splits": [
   "B3 (constraint-graded)",
   "M1 A1 A1"
  ]
 },
 "indices|mastery": {
  "n": 37,
  "mean": 1.78,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "inequalities|exam": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 (B1 per correct line, final mark for the region)",
   "M1 M1dep M1dep A1"
  ]
 },
 "inequalities|mastery": {
  "n": 14,
  "mean": 1.71,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "interquartile_range|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B1ft median + B1ft compare + B1ft IQR + B1ft compare"
  ]
 },
 "interquartile_range|mastery": {
  "n": 5,
  "mean": 2.6,
  "min": 2,
  "max": 4,
  "splits": [
   "B2 (B1 a value consistent with one stated relation)",
   "B1 B1"
  ]
 },
 "inverse_functions|exam": {
  "n": 2,
  "mean": 4.5,
  "min": 4,
  "max": 5,
  "splits": [
   "B1 B1 B1 B1",
   "M1 M1 M1dep M1dep A1"
  ]
 },
 "inverse_proportion|exam": {
  "n": 1,
  "mean": 5,
  "min": 5,
  "max": 5,
  "splits": [
   "M1 M1dep A1 M1 A1ft"
  ]
 },
 "inverse_proportion|mastery": {
  "n": 13,
  "mean": 1.54,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 (a correct point substituted with a verdict)",
   "B1 (tick meaning of constant)"
  ]
 },
 "irregular_and_improper_fractions|exam": {
  "n": 3,
  "mean": 3.33,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1 A1ft",
   "M1 A1 B1ft"
  ]
 },
 "irregular_and_improper_fractions|mastery": {
  "n": 5,
  "mean": 1.2,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 (mixed number required)"
  ]
 },
 "iteration|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "iteration|mastery": {
  "n": 4,
  "mean": 2.25,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 B1ft",
   "B1 (a converged value above the stated bound)"
  ]
 },
 "kinematic_graphs|exam": {
  "n": 3,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 interval read + M1dep gradient + A1",
   "B1 B1ft B1ft"
  ]
 },
 "kinematic_graphs|mastery": {
  "n": 11,
  "mean": 1.82,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "lengths_and_perimeters|exam": {
  "n": 4,
  "mean": 3.5,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1",
   "M1 A1"
  ]
 },
 "lengths_and_perimeters|mastery": {
  "n": 5,
  "mean": 1.6,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 (mark intention)",
   "B2 (B1 one correct perimeter)"
  ]
 },
 "loci|mastery": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "B4 (B1 per correct construction, final mark for the region)",
   "B3 semicircle ends radius 4 + connecting lines"
  ]
 },
 "lowest_common_multiple|mastery": {
  "n": 3,
  "mean": 1.33,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 two valid numbers (B1 one)"
  ]
 },
 "mean|exam": {
  "n": 5,
  "mean": 4.4,
  "min": 4,
  "max": 5,
  "splits": [
   "M1 M1 M1dep M1dep A1",
   "M1 M1 M1dep A1"
  ]
 },
 "mean|mastery": {
  "n": 14,
  "mean": 2.43,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "B1 (valid reason)"
  ]
 },
 "measuring_lines_and_angles|mastery": {
  "n": 8,
  "mean": 1.25,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 (range [54, 58])",
   "B1 (range [48, 52])"
  ]
 },
 "median|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "B3 (B1 per condition met)",
   "B1ft median + B1ft compare + B1ft IQR + B1ft compare"
  ]
 },
 "median|mastery": {
  "n": 10,
  "mean": 2.1,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1 (valid reason)"
  ]
 },
 "mode|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B3 (B1 per condition met)"
  ]
 },
 "mode|mastery": {
  "n": 3,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B2 (B1 a valid coin set or the modal value of their set)"
  ]
 },
 "nth_term_quadratic_sequences|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 (n-15)^2 + M1dep +11 form + A1 explanation"
  ]
 },
 "nth_term_quadratic_sequences|mastery": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1",
   "B3 (B2 two of the three coefficients, B1 one)"
  ]
 },
 "parts_of_a_circle|mastery": {
  "n": 9,
  "mean": 1.44,
  "min": 1,
  "max": 3,
  "splits": [
   "B1 B1 (name two regions)",
   "B1 region A + B1 region B"
  ]
 },
 "percentage_change|exam": {
  "n": 7,
  "mean": 4.57,
  "min": 4,
  "max": 5,
  "splits": [
   "M1 M1 M1 M1dep A1",
   "M1 M1dep M1 A1"
  ]
 },
 "percentage_change|mastery": {
  "n": 11,
  "mean": 2.91,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1",
   "M2 A1 (M1 correct first step)"
  ]
 },
 "perpendicular_gradients|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1"
  ]
 },
 "perpendicular_gradients|mastery": {
  "n": 4,
  "mean": 3,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 M1 M1dep M1dep A1",
   "M1 M1 M1dep A1"
  ]
 },
 "pie_charts|exam": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1"
  ]
 },
 "pie_charts|mastery": {
  "n": 7,
  "mean": 2.57,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B1 (No + valid reason)"
  ]
 },
 "plans_and_elevations|exam": {
  "n": 2,
  "mean": 2.5,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1 A1",
   "M1 A1"
  ]
 },
 "plans_and_elevations|mastery": {
  "n": 5,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1 (compute dim + draw)",
   "B2 (plan = circle)"
  ]
 },
 "plotting_straight_line_graphs|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 (B1 per correct line, final mark for the region)"
  ]
 },
 "plotting_straight_line_graphs|mastery": {
  "n": 5,
  "mean": 2.4,
  "min": 2,
  "max": 3,
  "splits": [
   "B2",
   "M1 M1 A1"
  ]
 },
 "prime_factor_decomposition|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B3"
  ]
 },
 "prime_factor_decomposition|mastery": {
  "n": 6,
  "mean": 2.33,
  "min": 1,
  "max": 3,
  "splits": [
   "B3 (B2 four of five conditions, B1 three)",
   "M1 M1dep A1"
  ]
 },
 "probability_spaces|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1ft"
  ]
 },
 "probability_spaces|mastery": {
  "n": 6,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 A1 A1ft (construct spinner + P)"
  ]
 },
 "properties_of_3d_solids|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1"
  ]
 },
 "properties_of_3d_solids|mastery": {
  "n": 9,
  "mean": 1.33,
  "min": 1,
  "max": 2,
  "splits": [
   "B2 (B1 tick alone)",
   "B1 (faces)"
  ]
 },
 "proportion_with_powers|exam": {
  "n": 3,
  "mean": 3.67,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep M1dep A1",
   "M1 M1dep A1 M1 A1ft"
  ]
 },
 "proportion_with_powers|mastery": {
  "n": 3,
  "mean": 2.67,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B1 (No + valid reason)"
  ]
 },
 "proportion|exam": {
  "n": 21,
  "mean": 3.57,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep M1 A1",
   "M1 A1"
  ]
 },
 "proportion|mastery": {
  "n": 30,
  "mean": 2.57,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 A1",
   "M1 M1dep A1"
  ]
 },
 "pythagoras_theorem|exam": {
  "n": 2,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 M1dep A1 A1ft"
  ]
 },
 "pythagoras_theorem|mastery": {
  "n": 8,
  "mean": 2.88,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "quadratic_functions|mastery": {
  "n": 14,
  "mean": 2.07,
  "min": 1,
  "max": 3,
  "splits": [
   "B2 (B1 one correct value)",
   "M1 A1"
  ]
 },
 "quadratic_inequalities|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B1 M1 A1ft B1ft"
  ]
 },
 "quadratic_inequalities|mastery": {
  "n": 2,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1 (identify the error)",
   "B1"
  ]
 },
 "range|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B3 (B1 per condition met)"
  ]
 },
 "range|mastery": {
  "n": 9,
  "mean": 2,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B3 (3 rows true/may-be-true/not-true)"
  ]
 },
 "ratio|exam": {
  "n": 17,
  "mean": 3.29,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "ratio|mastery": {
  "n": 38,
  "mean": 2.42,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B1"
  ]
 },
 "rearranging_formulae|exam": {
  "n": 3,
  "mean": 3.33,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "rearranging_formulae|mastery": {
  "n": 7,
  "mean": 2.57,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "B1"
  ]
 },
 "reciprocals|mastery": {
  "n": 4,
  "mean": 1.25,
  "min": 1,
  "max": 2,
  "splits": [
   "B1 (circle one of four)",
   "B1"
  ]
 },
 "recurring_decimals_to_fractions|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "recurring_decimals_to_fractions|mastery": {
  "n": 4,
  "mean": 2.5,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "B1 (circle one of four)"
  ]
 },
 "reflections|mastery": {
  "n": 6,
  "mean": 1.17,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (B1 a correct reflection without the mirror line)"
  ]
 },
 "relative_frequency|mastery": {
  "n": 12,
  "mean": 1.58,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "B1 (choice + valid reason)"
  ]
 },
 "reverse_percentage|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "reverse_percentage|mastery": {
  "n": 8,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "rotations|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 B1 B1 (name, angle or scale factor, centre)"
  ]
 },
 "rotations|mastery": {
  "n": 2,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "B2 (B1 angle or centre alone)",
   "B1 B1 (angle and vector)"
  ]
 },
 "rounding|mastery": {
  "n": 6,
  "mean": 1.5,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 B1 (pick from list of 4)"
  ]
 },
 "sampling|mastery": {
  "n": 3,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1 (reason)",
   "B1"
  ]
 },
 "scatter_graphs|exam": {
  "n": 3,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1ft",
   "B1 B1ft B1ft"
  ]
 },
 "scatter_graphs|mastery": {
  "n": 6,
  "mean": 1.5,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B1 (circle one of four)"
  ]
 },
 "sector_calculations|mastery": {
  "n": 7,
  "mean": 3,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "B1 (tick: smaller than part (a))"
  ]
 },
 "sequences|exam": {
  "n": 3,
  "mean": 2.67,
  "min": 2,
  "max": 3,
  "splits": [
   "B1 B1ft B1",
   "M1 A1"
  ]
 },
 "sequences|mastery": {
  "n": 23,
  "mean": 1.52,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1dep M1dep A1"
  ]
 },
 "significant_figures|mastery": {
  "n": 3,
  "mean": 2.33,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 M1 A1"
  ]
 },
 "simple_arithmetic|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep M1 A1"
  ]
 },
 "simple_arithmetic|mastery": {
  "n": 78,
  "mean": 2.49,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 M1dep M1dep A1"
  ]
 },
 "simple_charts|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "simple_charts|mastery": {
  "n": 16,
  "mean": 2.31,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 A1",
   "B1"
  ]
 },
 "simplifying_expressions|exam": {
  "n": 4,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 B1ft B1",
   "B3 (match algebra to description)"
  ]
 },
 "simplifying_expressions|mastery": {
  "n": 28,
  "mean": 2.11,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B2 (B1 one bracket expanded correctly)"
  ]
 },
 "simplifying_fractions|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 A1 B1ft"
  ]
 },
 "simplifying_fractions|mastery": {
  "n": 6,
  "mean": 2.17,
  "min": 1,
  "max": 4,
  "splits": [
   "B2 (B1 an unsimplified equivalent)",
   "M1 A1 B1ft"
  ]
 },
 "simplifying_indices|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 each of three simplified terms"
  ]
 },
 "simplifying_indices|mastery": {
  "n": 14,
  "mean": 1.93,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B1 B1 B1"
  ]
 },
 "simplifying_ratio|exam": {
  "n": 6,
  "mean": 2.83,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 A1ft"
  ]
 },
 "simplifying_ratio|mastery": {
  "n": 7,
  "mean": 2.43,
  "min": 1,
  "max": 4,
  "splits": [
   "M1 M1dep M1dep A1",
   "B1"
  ]
 },
 "simultaneous_equations_quadratic|exam": {
  "n": 1,
  "mean": 5,
  "min": 5,
  "max": 5,
  "splits": [
   "M1 equate + A1 quadratic + M1 solve + A1 x-values + A1 both coordinate pairs"
  ]
 },
 "simultaneous_equations|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "simultaneous_equations|mastery": {
  "n": 6,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "sine_rule|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1dep A1 A1ft"
  ]
 },
 "sine_rule|mastery": {
  "n": 3,
  "mean": 2.67,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "M1 A1"
  ]
 },
 "sketching_functions|mastery": {
  "n": 6,
  "mean": 1.83,
  "min": 1,
  "max": 2,
  "splits": [
   "B2 (B1 per valid criticism)",
   "B1 + B1"
  ]
 },
 "solving_linear_equations|exam": {
  "n": 11,
  "mean": 3.91,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 M1 M1dep M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "solving_linear_equations|mastery": {
  "n": 23,
  "mean": 2.04,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1dep A1"
  ]
 },
 "solving_quadratic_equations_factorising|exam": {
  "n": 8,
  "mean": 4.5,
  "min": 4,
  "max": 5,
  "splits": [
   "M1 M1dep M1 A1",
   "M1 A1 M1 A1ft A1"
  ]
 },
 "solving_quadratic_equations_factorising|mastery": {
  "n": 2,
  "mean": 2.5,
  "min": 1,
  "max": 4,
  "splits": [
   "B1 (either order)",
   "M1 expand + M1dep rearrange to =0 + M1 factorise/formula + A1 (-1 and 10)"
  ]
 },
 "solving_quadratic_equations_quadratic_equation|mastery": {
  "n": 4,
  "mean": 3.25,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 expand + M1dep equation + M1dep rearrange + A1 d,e,f"
  ]
 },
 "standard_form|exam": {
  "n": 4,
  "mean": 3,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 A1ft",
   "M1 M1dep A1"
  ]
 },
 "standard_form|mastery": {
  "n": 11,
  "mean": 1.73,
  "min": 1,
  "max": 3,
  "splits": [
   "B1",
   "B2"
  ]
 },
 "substitution|mastery": {
  "n": 22,
  "mean": 2.09,
  "min": 1,
  "max": 3,
  "splits": [
   "M1 A1",
   "M1 M1dep A1"
  ]
 },
 "surds_expanding_and_rationalising|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M2 A1 (M1 one or two correct exact values)"
  ]
 },
 "surds_expanding_and_rationalising|mastery": {
  "n": 2,
  "mean": 2.5,
  "min": 2,
  "max": 3,
  "splits": [
   "M1 M1dep A1",
   "M1 rationalise + A1 (4 root 5)"
  ]
 },
 "surds_simplifying|exam": {
  "n": 3,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 A1"
  ]
 },
 "surds_simplifying|mastery": {
  "n": 4,
  "mean": 2.25,
  "min": 1,
  "max": 3,
  "splits": [
   "B3 (B1 per correct match)",
   "B1"
  ]
 },
 "surface_area_of_a_cone|mastery": {
  "n": 2,
  "mean": 1,
  "min": 1,
  "max": 1,
  "splits": [
   "B1 (identify error)",
   "B1"
  ]
 },
 "surface_area_of_a_cylinder|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "surface_area_of_a_sphere|exam": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "symmetry|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4"
  ]
 },
 "symmetry|mastery": {
  "n": 7,
  "mean": 1.43,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (shade for 2 lines symmetry)"
  ]
 },
 "systematic_listing|exam": {
  "n": 3,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "B3 (constraint-graded)",
   "M1 M1 M1dep A1"
  ]
 },
 "systematic_listing|mastery": {
  "n": 8,
  "mean": 1.88,
  "min": 1,
  "max": 3,
  "splits": [
   "B2 (B1 three or four of the five correct)",
   "B2 (B1 one spinner fully labelled)"
  ]
 },
 "time_calculations|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1"
  ]
 },
 "time_calculations|mastery": {
  "n": 10,
  "mean": 2.1,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 M1 A1"
  ]
 },
 "time_series|exam": {
  "n": 2,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "B1 M1 A1ft"
  ]
 },
 "time_series|mastery": {
  "n": 10,
  "mean": 1.6,
  "min": 1,
  "max": 2,
  "splits": [
   "M1 A1",
   "B2 (B1 at least four points correct)"
  ]
 },
 "translations|mastery": {
  "n": 6,
  "mean": 1.5,
  "min": 1,
  "max": 2,
  "splits": [
   "B1",
   "B2 (B1 one component correct or a described translation)"
  ]
 },
 "tree_diagrams|mastery": {
  "n": 14,
  "mean": 2.14,
  "min": 1,
  "max": 4,
  "splits": [
   "B1 B1",
   "M1 A1"
  ]
 },
 "trig_graphs|mastery": {
  "n": 4,
  "mean": 1.25,
  "min": 1,
  "max": 2,
  "splits": [
   "B1 (tick one of four)",
   "B1 (258.69)"
  ]
 },
 "trigonometry_3d|mastery": {
  "n": 1,
  "mean": 3,
  "min": 3,
  "max": 3,
  "splits": [
   "M1 M1dep A1"
  ]
 },
 "trigonometry_missing_angles|mastery": {
  "n": 4,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "trigonometry_missing_sides|mastery": {
  "n": 10,
  "mean": 3.2,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 },
 "understanding_straight_line_graphs|exam": {
  "n": 2,
  "mean": 3.5,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 A1",
   "M1 M1 M1dep A1"
  ]
 },
 "understanding_straight_line_graphs|mastery": {
  "n": 24,
  "mean": 2.13,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "B1 (any parallel line, not the same line)"
  ]
 },
 "upper_and_lower_bounds|mastery": {
  "n": 18,
  "mean": 2.11,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B2 (B1 one bound in the correct position)"
  ]
 },
 "vector_proof|exam": {
  "n": 2,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "B5 (banded B1-B4 by which correct vectors are stated)",
   "M1 M1dep A1"
  ]
 },
 "vector_proof|mastery": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "M1 one expr + M1dep two exprs + A1 simplify + A1 parallel indication"
  ]
 },
 "vectors|exam": {
  "n": 2,
  "mean": 4,
  "min": 3,
  "max": 5,
  "splits": [
   "B5 (banded B1-B4 by which correct vectors are stated)",
   "M1 M1dep A1"
  ]
 },
 "vectors|mastery": {
  "n": 9,
  "mean": 1.89,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "B2 (B1 one component correct or a described translation)"
  ]
 },
 "venn_diagrams|exam": {
  "n": 1,
  "mean": 4,
  "min": 4,
  "max": 4,
  "splits": [
   "B4 (B1 per correct region)"
  ]
 },
 "venn_diagrams|mastery": {
  "n": 18,
  "mean": 1.72,
  "min": 1,
  "max": 4,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "volume_of_a_prism|exam": {
  "n": 6,
  "mean": 3.17,
  "min": 2,
  "max": 5,
  "splits": [
   "M1 A1",
   "M1 A1 A1"
  ]
 },
 "volume_of_a_prism|mastery": {
  "n": 5,
  "mean": 2.8,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 M1dep A1",
   "M1 M1 M1dep A1"
  ]
 },
 "volume_of_a_pyramid_and_cone|exam": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1"
  ]
 },
 "volume_of_a_pyramid_and_cone|mastery": {
  "n": 1,
  "mean": 2,
  "min": 2,
  "max": 2,
  "splits": [
   "M1 A1"
  ]
 },
 "volume_of_a_sphere|exam": {
  "n": 3,
  "mean": 3.67,
  "min": 3,
  "max": 4,
  "splits": [
   "M1 M1 M1dep A1",
   "M1 M1dep A1"
  ]
 },
 "volume_of_a_sphere|mastery": {
  "n": 4,
  "mean": 3,
  "min": 2,
  "max": 4,
  "splits": [
   "M1 A1",
   "M1 M1 M1dep A1"
  ]
 }
}

/** Fallback when a skill has too little evidence of its own. */
export const BY_KIND: Record<string, MarkStats> = {
 "mastery": {
  "n": 960,
  "mean": 2.01,
  "min": 1,
  "max": 5,
  "splits": [
   "B1",
   "M1 A1"
  ]
 },
 "exam": {
  "n": 135,
  "mean": 3.47,
  "min": 1,
  "max": 5,
  "splits": [
   "M1 M1dep A1",
   "M1 M1dep M1dep A1"
  ]
 }
}

/** Last-resort centre: every coded part, regardless of skill or kind. */
export const OVERALL: MarkStats = {
 "n": 1095,
 "mean": 2.19,
 "min": 1,
 "max": 5,
 "splits": []
}

/**
 * Average METHOD marks per part, by the part's mark total.
 *
 * Method marks are what a real scheme awards for a sound approach behind a wrong
 * answer — the credit auto-grading is blind to. Note the 1-mark row: a one-mark
 * part never carries method marks, which is what makes the blind spot bounded.
 */
export const METHOD_SHARE_BY_MARKS: Record<number, number> = {
 "1": 0,
 "2": 0.47,
 "3": 0.93,
 "4": 1.27,
 "5": 2.09
}
