-- ─────────────────────────────────────────────────────────────────────────────
-- Revoke client-role INSERT on students/teachers.
--
-- FOUND BY: introspecting column privileges on 2026-09-14, while gathering the
-- shape of `students` and `teachers` to capture them in version control
-- (docs/audit/20-school-accounts-design.md §7 step 2). The grant dump shows
-- anon AND authenticated holding INSERT, REFERENCES and SELECT on EVERY column
-- of BOTH tables.
--
-- 20260611_lock_sensitive_columns.sql revoked UPDATE, and only UPDATE:
--
--     revoke update on students from anon, authenticated;
--     revoke update on teachers from anon, authenticated;
--
-- The introspection confirms that worked — no UPDATE and no DELETE remains for
-- either client role. INSERT was never in scope of that migration and is still
-- granted.
--
-- ⚠ A LOAD-BEARING COMMENT SAYS OTHERWISE. app/api/auth/provision/route.ts
-- explains why it uses the service role with:
--
--     "client-role INSERT/UPDATE on these tables is REVOKE'd — see
--      20260611_lock_sensitive_columns.sql"
--
-- Half of that is false. The next person to reason about account creation would
-- have read it and concluded the INSERT path was already closed. This migration
-- makes the comment true; the same commit corrects its wording either way.
--
-- ── WHAT THE GRANT COULD BUY ────────────────────────────────────────────────
-- Grants are only half the gate — RLS decides the row — so the exposure depends
-- on the INSERT policies on these tables, which is the one piece of the
-- introspection not yet to hand. That is precisely why this is worth revoking
-- rather than reasoning about: with no table-level INSERT grant, the policy
-- question stops mattering. The privilege is checked BEFORE the policy.
--
-- Two things it would buy if any permissive INSERT policy exists:
--
--   1. Breaking the "a user is EITHER a teacher OR a student" invariant that
--      app/api/auth/provision/route.ts §3 goes out of its way to protect — a
--      teacher inserting a `students` row under their own id, or the reverse.
--      There is no unique constraint spanning the two tables to stop it.
--   2. `subscription_tier` and `paid_until` are insertable columns. An inserted
--      row is a row nobody paid for, and isPaidStudent reads exactly those two
--      columns for the personal grant.
--
-- ── WHY THIS IS SAFE WITH NO CODE CHANGE ────────────────────────────────────
-- Same argument 20260611 made for UPDATE, re-checked for INSERT. There are ZERO
-- client-side inserts into either table anywhere in app/, lib/ or scripts/. All
-- 31 `.from('students'|'teachers')` call sites are either reads or run under
-- the SERVICE ROLE, which bypasses grants entirely:
--
--   * app/api/auth/provision/route.ts — the Google OAuth path, service role
--   * app/api/stripe/webhook/route.ts — service role
--
-- Email/password signup does not touch these grants either: the rows come from
-- handle_new_user / handle_new_student, which are SECURITY DEFINER (see
-- 20260913_auth_signup_triggers.sql) and so run as the definer, not the caller.
--
-- Account creation is therefore unaffected by this change, on BOTH paths.
--
-- ── DELIBERATELY NOT CHANGED ────────────────────────────────────────────────
--
-- 1. SELECT stays. The student dashboard reads the student's own row from the
--    browser, and RLS scopes it to that row. Worth a separate look later:
--    app/student/dashboard/page.tsx uses `.select('*')`, so a student's own
--    stripe_customer_id and stripe_subscription_id are shipped to their own
--    browser. That is their own data and low severity, but narrowing the grant
--    to the columns the UI needs would mean editing the `select('*')` call
--    sites, which is a behavioural change and does not belong here.
--
-- 2. REFERENCES stays. Supabase grants it by default. Exploiting it needs CREATE
--    on a schema in order to make the referencing table, which neither client
--    role has. Recorded rather than fixed, to keep this change to one idea.
--
-- 3. No capture of the table definitions. That is its own file, and PR #71 set
--    the rule this follows: a file that records what already exists must not
--    also change behaviour.
--
-- Apply via the Supabase SQL Editor (DDL constraint). Idempotent. No code
-- change is required for it, and no deploy ordering applies.
-- ─────────────────────────────────────────────────────────────────────────────

begin;

revoke insert on students from anon, authenticated;
revoke insert on teachers from anon, authenticated;

commit;

-- ── Verify after applying ────────────────────────────────────────────────────
--
-- 🚨 DO NOT verify by inserting from the SQL Editor. It runs as SUPERUSER,
-- which bypasses both grants and RLS, so the insert would succeed regardless
-- and tell you nothing. This fix lives entirely in the grant layer and is
-- invisible to a superuser. The same trap is documented at the foot of
-- 20260727_class_membership_scope.sql.
--
-- (a) Read the grants back. EXPECT only REFERENCES and SELECT to remain:
--
--       select table_name, grantee, privilege_type
--       from information_schema.table_privileges
--       where table_schema = 'public'
--         and table_name in ('students','teachers')
--         and grantee in ('anon','authenticated')
--       order by table_name, grantee, privilege_type;
--
-- (b) Impersonate the client role. `begin/rollback` writes nothing, so this is
--     safe against production. Substitute the uuid of a real TEACHER account:
--
--       begin;
--         set local role authenticated;
--         set local request.jwt.claims = '{"sub":"<TEACHER_UUID>"}';
--
--         -- EXPECT ERROR 42501. Before this migration it would have been
--         -- decided by the RLS policy instead, and a teacher holding a
--         -- students row breaks the either/or invariant.
--         insert into students (id, display_name, confirmed_13)
--         values ('<TEACHER_UUID>', 'x', true);
--       rollback;
--
-- (c) Smoke-test both real signup paths, which must keep working:
--     email/password at /auth?mode=signup (trigger path), and Continue with
--     Google (service-role path through /api/auth/provision).
